config/routes.rb
Linkding::Application.routes.draw do
  resources :bookmarks, except: :show do
    get :recent, on: :collection
    get :search, on: :collection
  end
  resource :import, only: [:show, :create], controller: 'Import'

  devise_for :users

  root to: 'home#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :site
  belongs_to :user
  belongs_to :import

  validates :url, presence: true, length: {maximum: 2048}
  validates :title, presence: true, length: {maximum: 1024}
  validates_uniqueness_of :site_id, scope: :user_id

  acts_as_taggable

  scope :public_visible, where(public: true)

  scope :recent, ->(limit = 100) { order("id DESC").limit(limit) }

  after_validation :set_tag_array

  def self.find_by_url(url)
    joins(:site).where("sites.url" => url).first if url
  end

  def self.active_tags
    tag_counts.order('count desc')
  end

  def self.recent_tags
    ActsAsTaggableOn::Tag.joins(:taggings)
      .where("taggings.taggable_id IN (#{scoped.select("id").to_sql})")
      .where(taggings: {taggable_type: "Bookmark", context: "tags"})
  end

  def self.active_tag_names
    recent_tags.group("tags.id").order("count(tags.id) DESC").select("tags.name")
  end

  def self.search(query, language = 'english')
    columns = [
        "title",
        "coalesce(description, '')"
    ]

    tsvector_sql = columns.map { |c| "to_tsvector('#{language}', #{c})" }.join(" || ")
    tsvector_sql << " || array_to_tsvector('#{language}', tag_array)"
    where("#{tsvector_sql} @@ plainto_tsquery('#{language}', ?)", query)
  end

  def url=(url)
    self.site = Site.find_or_create_by_url(url)
  end

  def url
    self.site.try(:url)
  end

  def copy_as_new
    Bookmark.new(url: self.url, title: self.title, description: self.description, tag_list: self.tag_list)
  end


  def set_tag_array
    self.tag_array = self.tag_list
  end
end

app/models/import.rb
class Import < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks
end

app/models/import_form.rb
class ImportForm
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :file

  validates_presence_of :file

  def initialize(attributes = {})
    attributes ||= {}
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/site.rb
class Site < ActiveRecord::Base
  validates_length_of :url, maximum: 2048
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,# :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         # :omniauthable,
         :timeoutable, :lockable, :token_authenticatable,
         :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me

  has_many :bookmarks
  has_many :imports

  def active_tags
    bookmarks.recent.active_tags
  end

  def active_tag_names
    bookmarks.recent.active_tag_names
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
  before_filter :authorize_mini_profiler

protected

  def authorize_mini_profiler
    if current_user.try(:admin?)
      Rack::MiniProfiler.authorize_request
    end
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < InheritedResources::Base
  actions :all, except: :show

  has_scope :tagged_with, as: 'tag'
  has_scope :page, default: 1, only: [:index, :recent]
  has_scope :search, only: [:index, :recent], as: 'q'
  before_filter :read_tags, only: [:new, :create, :edit, :update]

  def new
    if params[:bookmark] && bookmark = current_user.bookmarks.find_by_url(params[:bookmark][:url])
      redirect_to edit_bookmark_path(bookmark)
    else
      if params[:copy_id]
        @bookmark = Bookmark.find(params[:copy_id]).copy_as_new
      end
      new!
    end
  end

  def index
    # TODO: refactor tag list into a cell as soon as we have Cells
    @tags = current_user.active_tag_names.limit(20)
    @bookmarks = collection.where(user_id: current_user)

    fresh_when last_modified: last_modified(@bookmarks)
  end

  def recent
    @bookmarks = apply_scopes(Bookmark).public_visible.includes(:site, :user).order("bookmarks.created_at desc")
    @tags = Bookmark.public_visible.limit(100).active_tag_names.limit(20)

    fresh_when last_modified: last_modified(@bookmarks)
  end

  protected

  def collection
    @bookmarks ||= end_of_association_chain.includes(:site, :user).order("bookmarks.created_at desc")
  end

  def begin_of_association_chain
    current_user
  end

  def read_tags
    @tags = current_user.active_tags.limit(100)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to bookmarks_path, notice: flash[:notice]
  end
end

app/controllers/import_controller.rb
class ImportController < ApplicationController
  def show
    @import_form = ImportForm.new
  end

  def create
    @import_form = ImportForm.new(params[:import_form])

    unless @import_form.valid?
      render :show
      return
    end

    dom = Nokogiri::HTML(@import_form.file.read)
    success_count = 0
    failure_count = 0
    import = Import.create!(user: current_user)
    dom.xpath('//dt/a').each do |a|
      begin
        next_element = next_element(a)
        description = (next_element.content if next_element.try(:name) == "dd")
        url = a['href'].try(:strip)
        Bookmark.create!(
            user: current_user,
            url: url,
            title: a.content.try(:strip).truncate(1024),
            description: description.try(:strip),
            tag_list: filter_tags(a['tags']),
            public: a['private'] == "0",
            created_at: Time.at(a['add_date'].to_i),
            import: import
        )
        success_count += 1
      rescue Exception => e
        failure_count += 1
        logger.info("Import #{import.id}, url: #{url.inspect}: #{e}")
      end
    end

    notice = if failure_count == 0
      I18n.translate('import.success', success_count: success_count)
    else
      I18n.translate('import.skipped', success_count: success_count, failure_count: failure_count)
    end

    redirect_to bookmarks_path, notice: notice
  end

  private

  def filter_tags(input)
    # Remove delicious share tags since this information should not be public
    blacklist = /for\:.+/
    input.split(",").map(&:strip).reject { |tag| tag =~ blacklist }.join(",") if input.present?
  end

  def next_element(node)
    node.next_element || next_element(node.parent) unless node.nil?
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def bookmarklet
    render "tools/bookmarklet.js", layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar(user, options = {})
    size = options.delete(:size) || 60
    https = options.delete(:https)
    base_url = https ? "https://secure.gravatar.com" : "http://www.gravatar.com"
    image_tag "#{base_url}/avatar/#{Digest::MD5.new.hexdigest(user.email.downcase)}?s=#{size}", options.merge(alt: "")
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_bookmark.html.haml
= content_tag_for(:section, bookmark, class: bookmark.public ? 'public' : 'private') do
  %h3= link_to bookmark.title, bookmark.url
  .link
    = link_to truncate(bookmark.url, length: 90), bookmark.url, target: '_blank', class: 'link'
  - if bookmark.description.present?
    .description
      = simple_format bookmark.description
  - if bookmark.tag_array.any?
    .tags
      - bookmark.tag_array.each do |tag|
        = link_to(tag, bookmarks_path(tag: tag), class: 'tag')

  .info
    %span.date{title: l(bookmark.created_at)}
      = t('.time_ago', time: time_ago_in_words(bookmark.created_at))
    %span.author
      - if user_signed_in? && bookmark.user == current_user
        = t('.by_me')
      - else
        = t('.by_author', author: bookmark.user.username)
  - if user_signed_in? && bookmark.user == current_user
    .links
      = link_to t('edit'), edit_bookmark_path(bookmark), class: 'edit'
      = link_to t('destroy'), bookmark, :confirm => t('confirm'), :method => :delete, class: 'destroy'
  - if user_signed_in? && bookmark.user != current_user
    .links
      = link_to t('.copy'), new_bookmark_path(copy_id: bookmark.id), class: 'copy'

app/views/bookmarks/_form.html.haml
= simple_form_for(@bookmark) do |f|
  = f.error_notification

  .inputs
    = f.input :url
    = f.input :title
    = f.input :description
    = f.input :tag_list, input_html: {data: {autocomplete: @tags.map(&:name)}}
    = f.input :public

  .actions
    = f.submit

app/views/bookmarks/_search_form.html.haml
%section.search
  %h2 Search
  = form_tag Hash.new, method: :get, class: 'search_form' do
    = label_tag :q, "Search"
    = text_field_tag :q, params[:q], placeholder: "Search"
    = submit_tag "Go", name: nil

app/views/bookmarks/_tag_list.html.haml
%h2 Tags
%ul.tags
  - @tags.pluck(:name).each do |tag|
    %li.tag= link_to tag, tag: tag

app/views/bookmarks/edit.html.haml
%h1= t('.title')

= render 'form'

= link_to t('back'), bookmarks_path, id: "backlink"

app/views/bookmarks/index.html.haml
%h1= t('.title')

= paginated_section @bookmarks do
  = render @bookmarks

= link_to t('.new'), new_bookmark_path

- content_for :sidebar do
  = render 'search_form'
  = render 'tag_list'

app/views/bookmarks/new.html.haml
%h1= t('.title')

= render 'form'

= link_to t('back'), bookmarks_path, id: "backlink"

app/views/bookmarks/recent.html.haml
%h1= t('.title')

= paginated_section @bookmarks do
  = render @bookmarks

- content_for :sidebar do
  = render 'search_form'
  = render 'tag_list'

app/views/bookmarks/search.html.haml
%h1 Search

= form_tag search_bookmarks_path, method: :get do
  = text_field_tag :q, params[:q]
  = submit_tag "Search", name: nil

= paginated_section @bookmarks do
  = render @bookmarks

-# content_for :sidebar do
  = render 'tag_list'

app/views/import/show.html.haml
%h1= t('.title')

= simple_form_for(@import_form, url: import_path, multipart: true) do |f|
  .inputs
    = f.input :file, as: :file
  .actions
    = f.submit t('.submit')

= link_to t('back'), bookmarks_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Linkding
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags
    %meta{charset: 'UTF-8'}
    %meta{name: 'viewport', content: 'width=device-width,initial-scale=1.0,maximum-scale=1.0'}
    = auto_discovery_link_tag(:atom, bookmarks_path(format: 'atom'), title: "My Bookmarks")
    = auto_discovery_link_tag(:atom, recent_bookmarks_path(format: 'atom'), title: "Recent Bookmarks")
    = yield :head
    = javascript_include_tag "application"
  %body
    %header#header
      .container
        .main
          %h1#logo= link_to "Linkding", root_path

          %nav#navigation
            %ul
              - if user_signed_in?
                %li= link_to t('layout.add_bookmark'), new_bookmark_path
                %li= link_to t('layout.my_bookmarks'), bookmarks_path
                %li= link_to t('layout.recent_bookmarks'), recent_bookmarks_path
                %li= link_to t('layout.import'), import_path

        %nav#account-nav
          - if user_signed_in?
            = avatar(current_user, id: 'avatar', https: true)
            .account
              = current_user.email
            = link_to t('layout.sign_out'), destroy_user_session_path, class: "signout"
          - else
            = link_to t('layout.sign_in'), new_user_session_path, class: "signin"

    #main
      .container
        #content{class: content_for?(:sidebar) ? 'has_sidebar' : 'no_sidebar'}
          - flash.each do |name, msg|
            = content_tag :div, msg, id: "flash_#{name}", class: 'flash'
          = yield
        - if content_for? :sidebar
          #sidebar
            = yield :sidebar

app/views/tools/bookmarklet.js.erb
CSRFTOKEN = '<%= form_authenticity_token %>';

var LinkdingBookmarklet = {
  version: '0.1',
  url: '<%= root_url %>',

  init: function (version, page) {
    LinkdingBookmarklet.showBookmarklet();
  },

  showBookmarklet: function () {
    var form = document.createElement('form');
    form.method = 'POST';
    form.action = '<%= bookmarks_url %>';
    form.target = 'ldbmliframe';
    form.style.display = 'none';

    var field = document.createElement('input');
    field.name = 'authenticity_token';
    field.type = 'text';
    field.value = CSRFTOKEN;
    form.appendChild(field);

    var field = document.createElement('input');
    field.name = 'bookmark[url]';
    field.type = 'text';
    field.value = window.location;
    form.appendChild(field);

    var field = document.createElement('input');
    field.name = 'bookmark[title]';
    field.type = 'text';
    field.value = window.document.title;
    form.appendChild(field);

    var field = document.createElement('input');
    field.name = 'bookmark[description]';
    field.type = 'text';
    field.value = (window.getSelection ? window.getSelection() : (document.getSelection ? document.getSelection() : (document.selection ? document.selection.createRange().text : '')));
    form.appendChild(field);

    var ifr = document.createElement('iframe');
    ifr.id = 'ldbmliframe';
    ifr.name = 'ldbmliframe';
    ifr.src = ' ';
    ifr.setAttribute("style", "position: absolute; top: 0; left: 0; width: 100%; background: #fff; z-index: 5000; border-bottom: 5px solid #000;");

    document.body.appendChild(form);
    document.body.appendChild(ifr);

    form.submit();
  }
};

function ldbmlinit(version) {
  LinkdingBookmarklet.init(version);
}